### ISSUE TITLE
Duplicated notifications

### ISSUE THREAD

**Issue by ngosang** [gotify/android#242]
One month ago I started receiving duplicated notifications/messages in my phone. Before that it was working as expected.
* This only happens in Android client, the Web UI is working well.
* There are not error traces in the client nor the server. I don't see duplicated traces, all is fine.
* If I refresh the notifications in the Android client the duplicate notifications disappear.
* Both notifications appear at the same time
* I'm I heavy user (100 notifications a day)

![Screenshot_2022-08-21-09-25-17-48_f78104b9cb08305e57e6798400aed5f9](https://user-images.githubusercontent.com/10577978/185780531-74a2cb9c-0190-444b-b15e-112c937d47e0.jpg)
![Screenshot_2022-08-21-09-25-58-34_f78104b9cb08305e57e6798400aed5f9](https://user-images.githubusercontent.com/10577978/185780534-e40b6203-2eb2-47cb-8040-8a06b2d09fb5.jpg)

**Comment by jmattheis** [comment]
Could you post the log from the android app around the time a duplicated notification occurred?

**Comment by ngosang** [comment]
There are no traces at that moment.

**Comment by jmattheis** [comment]
Every message will be logged. Are you looking inside the built-in logging view in the android app?

![image](https://user-images.githubusercontent.com/14895212/185805271-470f8110-295f-415e-b4a7-4aac1b14b638.png)

something like this should be in there:
```
2022-08-21T18:18:12.414Z INFO: WebSocket(3): received message {"id":183,"appid":10,"message":"oops","title":"Test","priority":5,"extras":{"client::display":{"contentType":"text/markdown"}},"date":"2022-08-21T20:18:12.460258394+02:00"}

2022-08-21T18:18:09.005Z INFO: Entering LogsActivity
2022-08-21T18:18:06.927Z INFO: Loading more messages for -1
2022-08-21T18:18:06.920Z INFO: Entering MessagesActivity
2022-08-21T18:18:06.872Z INFO: WebSocket(3): opened
2022-08-21T18:18:06.864Z INFO: Server version: 2.1.5@2022-07-31-09:16:46
2022-08-21T18:18:06.859Z INFO: WebSocket(3): starting...
2022-08-21T18:18:06.855Z INFO: Starting WebSocketService
```

**Comment by ngosang** [comment]
Everything looks fine. There are no duplicate traces in the client.
For each trace I see 2 messages in the Gotify like in the first post. I don't know the cause but it looks like a rendering issues since it's fixed if I scroll to refresh.
```
2022-08-22T12:17:00.777Z INFO: WebSocket(9): received message {"id":25175,"appid":6,"message":"Report 356...","title":"XRT Report","priority":10,"date":"2022-08-22T14:17:01.770665451+02:00"}
2022-08-22T11:45:55.119Z INFO: WebSocket(9): received message {"id":25174,"appid":8,"message":"SeekingAlpha...","title":"RSS","priority":5,"date":"2022-08-22T13:45:56.030672749+02:00"}
2022-08-22T11:45:55.023Z INFO: WebSocket(9): received message {"id":25173,"appid":8,"message":"TuCapital\....","title":"RSS","priority":5,"date":"2022-08-22T13:45:56.012680205+02:00"}
2022-08-22T10:00:54.959Z INFO: WebSocket(9): received message {"id":25172,"appid":8,"message":"Tor....","title":"RSS","priority":5,"date":"2022-08-22T12:00:56.003322161+02:00"}
```
Check at the time. Old and new articles are mixed.
![image](https://user-images.githubusercontent.com/10577978/185954778-39ade648-f0bf-47c5-9284-d09021a67b21.png)

**Comment by jmattheis** [comment]
Can you reproduce this, like pushing a new message to gotify and then seeing the duplicated message in the app, or does it happen randomly?

**Comment by ngosang** [comment]
I can't reproduce the issue but its still happening from time to time. Log traces are clean, the messages are received only once but sometimes they are rendered 2 times.

**Comment by axllent** [comment]
I have the exact same issue. Not all messages, not always, but often enough to be annoying (several times a day). I can't share the logs but I can confirm that the duplicated messages only appear once in the logs.  If I refresh Gotify (pull down) the duplicated messages disappear.

**Comment by cyb3rko** [comment]
For me the duplicate notifications appear if I have multiple app versions of Gotify installed on my phone (release and development builds for example).

**Comment by ngosang** [comment]
I'm closing since I can't reproduce this issue in the new smartphone. I think it was related to an old version of Android.

**Comment by axllent** [comment]
I still get duplicate messages fairly regularly, despite a recent switch to a new high-end phone with the latest Android. The change of phone made no difference in my case.

**Comment by cyb3rko** [comment]
There is a possibility that this problem is fixed with the next update, but no guarantee here.

**Comment by Pikaro** [comment]
This is 100% reproducible for me. I implemented a websocket listener that responds with `pong` if I send a message `ping` from my mobile. (Intended to execute actions on the host system if it proves reliable.) It only sends once, and the message is only logged once, but it is shown twice in the UI - one of them _before_ the ping message I also see in the mobile app. (I. e. I see `pong`, `ping`, `pong`.) If I refresh, the first message disappears.

**Comment by jmattheis** [comment]
@Pikaro 

1. Can you post the log of your application, the gotify/server log and the gotify/android log at the time when this bug occurs for you?
1. Can you try to force close gotify/android and then recheck if the problem still occurs?
1. Do you have another version of gotify/android installed (like the development build or an older version)
1. What android version are you using?

I've tried reproducing this, but it works fine for me.

[pong.webm](https://github.com/gotify/android/assets/14895212/eab62ccc-34b2-41db-81e1-2f5efe0ec263)

**Comment by axllent** [comment]
@cyb3rko I'm just putting it out there, but I haven't experienced any duplicate notifications for a couple of months at least, so I'm thinking that update you were referring to fixed the issue for me at least.

**Comment by cyb3rko** [comment]
Should we close this one?  
It seems @ngosang and @axllent don't have this issue anymore.

**Comment by axllent** [comment]
I have actually _noticed_ it (since my last post) once, so I think it may still happen very rarely. Still no idea what causes it, nor how to replicate it to be honest. The fact is that I was experiencing it all-the-time (daily) before, and now almost never, so I'm happy to close this (it's not my call though, nor did I open this issue) :+1:

**Comment by cyb3rko** [comment]
If it still happens, we should keep this issue open

**Comment by appiekap653** [comment]
I also experience duplicate notifications. 
Almost every day.
But for me not at the same time.

I get a notification on my Android phone and delete the message in the Android app.
If I go to the webui, It shows that there are no messages present.
Then the next day I recieve exactly the same notification again on my phone.
The duplicated notification gets send along when there is a new notification from some other source.

Example:
```
Day 1: App-A sends notification 1 -> Phone shows notification 1 -> Delete notification 1.

Day 2: App-B sends notification 2 -> Phone shows notification 2 from App-B and notification 1 from App-A.
```

Client:
Phone: Samsung s21fe
Android version: 14
OneUI: 6.1
Gotify Android: 2.7.1

Server:
All as Docker containers.
Gotify: 2.5.0
Traefik: 3.1.6

**Comment by cyb3rko** [comment]
And the duplicated notification does not appear in the web UI, only on the phone?  
For me it somehow sounds like the problem would be server-related or related to the producer of the notifications.

Because the Android app only consumes a websocket and reacts to new notifications.

**Comment by appiekap653** [comment]
I only know that when the notifications are removed in the Android app, they are also removed from the webui.

I have to check if they reappear in the webui at the time that the Android app shows it again the next day. 

I will get back to you when I have received the duplicated notification.

**Comment by axllent** [comment]
FYI @jmattheis - I believe this has **finally** been fixed via your changes in d6cd95a89c2ddef7f5373825f2afc5503bfec3f8 - I was getting duplicate messages on a daily basis (often multiple times a day), but I have not received a single duplicate since the last release 3 weeks ago 🥳

**Comment by jmattheis** [comment]
@axllent Thanks for the update, Glad it works now!
